### PR TITLE
Update ImageCore to 0.9

### PR DESCRIPTION
**Pull request by Octogonapus**
This PR updates ImageCore to 0.9 since it was released today.

### CODE REVIEW

**Comment by Octogonapus** [comment]
@kdw503 Could you please take a look at this?

**Comment by Octogonapus** [comment]
@kdw503 Do you think this could be merged?

**Comment by kdw503** [comment]
@timholy is it ok to merge this?

**Comment by IanButterworth** [comment]
bump

**Comment by IanButterworth** [comment]
bump 🙏🏻

**Pull request merged**
